name: Feature request
description: Suggest an idea for Points
title: "[FEATURE]: "
labels: ["feature"]
body:
  - type: input
    id: contact
    attributes:
      label: Discord Username
      description: Giving us a discord username will help us reach out if we need more information
      placeholder: ex. Ad–∞m#2917
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What's your idea?
      description: Give us a detailed description of what you would like added.
      placeholder: Tell us what to add!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you want

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
